* Song Architecture
** Data Types
*** Numbers
Numbers are decimal floating-point numbers, counting from 1.

~8m, 8c, .8, 8, 80, 8h, 8k~ are all possible power levels, in order.
They're stackable; ~.1m~ considered valid, etc.
Using only + or - will increment or decrement the value.
Numbers default to 0 unless otherwise specified.

*** Bools
~y/t/1~ is true. ~n/f/0~ false.

*** id's
id's are in a base32, which is [0-9], plus [A-Z] minus O, I, Z, and S.
However, all of [A-Z], [a-z], and [0-9] are considered valid.
Lowercase chars are converted to uppercase, and O->0, I->1, Z->2, and S->5.
It is best to simply enter what's comfortable, rather than matching the display.
A direct listing of id's is in res/base32.

An id is typically short for a string name.
Non-base32 chars are ignored.
If you want to make an instrument unique, you can number it.
Non-entered id's default to "0".

examples
#+BEGIN_EXAMPLE
"piano"
  p, pi, pia, ... = piano

"that", "this" <--bad names
  t, th, ... = that
  thi, ... = this

"0that", "1this"
  o = 0that
  i = 1this
#+END_EXAMPLE
*** Macros
Macros are playback commands executed one tick per command.
Every channel always has an active macro.

Syntax
#+BEGIN_EXAMPLE
^i     simply set this macro to id i
[num]  single-digit numbers play a note at base note + n, then tick
.n     tick n times; default 1
+n     add n to the base note; default 1
-n     subtract n from the base note; default 1
>      add half an octave to the base note
<      subtract half an octave from the base note
N      new note
O      note off
K      note off, end macro here
E      end macro (otherwise repeat)
#+END_EXAMPLE

Examples
#+BEGIN_EXAMPLE
037      arpeggio triplet
<037     lower triplet
N        repeat note forever
.K       delay note off by 1
.2K      delay note off by 2
+1       glissando up
-1       glissando down
#+END_EXAMPLE

** Instruments
Instruments are commands that replace any part of the channel state.
They can have arbitrary precision/size; for example 48.3002 is valid here.

Example
#+BEGIN_EXAMPLE
  init: 3 41h 548k 6 7 8 9 g ha-
  note: p a50
#+END_EXAMPLE

Inferred meaning
#+BEGIN_EXAMPLE
init          ; do the following on instrument load
  30 4100     ; 100 long sample at 0
  548000      ; sample rate 48khz
  60 7100     ; loop entire sample
  8f          ; loop forward
  9100        ; no volume adjustment
  gc1 ha-1    ; patch to ramp volume down over 1 second

note          ; do the folowing on each note played
  p0          ; play from start of sample
  a50         ; start at 50% mixer volume
#+END_EXAMPLE

** Song data
Songs are stored in a whitespace-aware plaintext.
They're almost exactly what you see in the tracker.
See example-song for what they could look like.

*** Patterns
Every pattern of a song has a name that's referencable as an id.

Command format ~N-O / cXXXX~
#+BEGIN_EXAMPLE
N   note letter
O   octave
c   the base id; what to modify
X   4 chars of params
#+END_EXAMPLE

*** Order
Syntax
#+BEGIN_EXAMPLE
[id]    which order to play
[       start of loop
]       end of loop
#+END_EXAMPLE

Examples
#+BEGIN_EXAMPLE
[ a b a c ]    traditional song structure
intro [body]   a song with an intro and body
#+END_EXAMPLE
** List of Commands/Params
*** Internal
~0n~ live channel *0utput*. Set by song if ~4~ > 0 and ~5~ > 0.

~1i~ load *1nstrument*. Sets and initializes. Default ~2~.
Numbers used below because instruments typically consist of 1, 2, 3, 4, 5...

~2i~ set instrument. Sets w/o initializing.

~3n~ sample offset in points.

~4n~ sample length.

~5n~ *5ample* rate. Controls how quickly phase ~p~ increases.
Pitch at which A0 = 440hz. Default 16000.

~6n~ loop start relative to sample offset ~3~.

~7n~ loop length. Default is sample length ~4~.

~8L~ loop type. f=forward (default); p=pingpong; b=backward.
In any looping mode, looping is achieved by modulus-ing the phase by the
same size every time.
In pingpong mode, phase ~p~ has doubled range and "folds" on itself.

~9n~ volume base multiplier = n / 100. Default 100 = 1x

*** Playback
~An~ *Amplitude*; mixer volume. Ratio = n / 800. Default 100=1/8.

~Dn~ panning *Direction*. d100=fully right, d-100 = fully left.

~Tn~ *Tuning* adjustment. t100=full note up.

~Pn~ live *Phase* in points. Set if ~4~ > 0  and ~5~ > 0.

~Nn~ whole *Note* pitch, typically set by note column. Rounds to integers.

~Mm~ *macro* m. Default ~0E~; play note once.

*** Patches
Patches use a set of input/output fixed pairs: ~EF / GH / JK~.
Input data is read to each respective output per-sample.

~[E/G/J]*~ Input
#+BEGIN_EXAMPLE
Cn      constant value n (default 1)
[num]d  channel num, delay d in ms
Ad      the final mix, delay d in ms
Ln      an LFO n ticks per sample
#+END_EXAMPLE

~[F/H/K]O*~ Output
#+BEGIN_EXAMPLE
 O   output param to modify
 *   modify method
   wn   output = wet/dry mix;  0=dry, 100=wet; default=50
   >n   output = base + input * n/100
   <n   output = base - input * n/100
   =n   base = input * n/100; default 100=1.0
   +n   base = base + input * n/sample rate, default 1 = 1 second from 0 -> 1
   -n   base = base - input * n/sample rate, default 1 = 1 second from 1 -> 0
#+END_EXAMPLE
Things that modify the base will repeatedly and instantly modify.
This is affected by sample rate, and is divided by it for consistency.
However, things that modify output do so right before mixing, and cannot be stacked.

Examples
#+BEGIN_EXAMPLE
G.... HA-..  volume slide down 1/10000 per point
G0... HP...  total phase modulation from channel 0
G0... HTW20  frequency modulation from channel 0
G01K. H0W10  mix 1000-sample delayed channel 0 into self
#+END_EXAMPLE

*** Channel Misc
~Wn~ sample rate at which to grab history, default 16000

~XCb~ *Clipping* mode for mixer, 1=limit to [-1, 1]

*** Control
~JRn~ next *Row Jump*

~JPn~ next *Pattern Jump*

~Bn~ song *BPM*

~Rn~ set row *Rate*; ticks per row

~Vn~ global *volume*

*** Unused
~CLQUY<>+-^.~ What could they be for?

* Playback
** Mixing procedure
For each channel:
 1. If ~P~ (phase) is within sample, increase it according to ~N~, ~T~, ~5~.
 2. Fetch index ~P~ from current sample ~3~, ~4~.
 3. Multiply that by ~9~, clip if ~XC~, and write into ~0~.
 4. Run all controllers in order E, G, J.
 5. Store the output value, seeable by controller in the next channel.

After running all channels:
 1. Mix by multiplying channel output values by their amplitude ~A~ and pan ~D~.
 2. Store this value usably.
 3. Multiply that value by ~V~ and play it.

** On each row
 1. Set position to ~JR~, ~JP~.
 2. Set ~JR~, ~JP~ according to order.
 3. If command ~1~, run specified instrument, clear ~1~, and set ~2~.
 4. If note, set ~N~. If key-off, set macro to "~K~", else ~M~.
 5. Run row command.
 6. Set intervals for the given BPM ~B~, tickrate, and row rate ~R~.
